name: "PR Checks"
on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

defaults:
  run:
    shell: bash

concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  debug:
    runs-on: ubuntu-latest
    name: Debug the job
    steps:
      - uses: hmarr/debug-action@v2
  unit-label-check:
    name: "Label Check [CI:UnitTests]"
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'CI:UnitTests') || contains(github.event.pull_request.labels.*.name, 'CI:FinalChecks') }}
    steps:
      - name: Check Labels
        if: github.event_name == 'pull_request_target'
        run: echo Labels that trigger this build are [CI:UnitTests] and [CI:FinalChecks] 
